// Built-in initial achievements data transcribed from whiteboard
// Serves as instant fallback if backend is offline or opened via file:// protocol
const INITIAL_ACHIEVEMENTS = [
  {
    "id": "ach-2023-sih",
    "year": 2023,
    "title": "Smart India Hackathon (SIH) 2023",
    "position": "Winner",
    "awardTier": "winner",
    "category": "National Flagship Hackathon",
    "organization": "MoE & AICTE, Govt. of India",
    "description": "Crowned Grand Champions at India's largest nationwide open innovation initiative, competing against thousands of premier teams across the country.",
    "badge": "🏆 1st Prize Winner",
    "featured": true,
    "tags": ["SIH", "National", "Govt of India", "Flagship"]
  },
  {
    "id": "ach-2024-arjuna",
    "year": 2024,
    "title": "Arjuna 1.0",
    "position": "Winner",
    "awardTier": "winner",
    "category": "Project Competition & Hackathon",
    "organization": "Technical Symposium",
    "description": "Secured 1st position with high-impact software architecture and innovative engineering execution.",
    "badge": "🏆 Winner",
    "featured": true,
    "tags": ["Hackathon", "1st Place", "Innovation"]
  },
  {
    "id": "ach-2024-esummit",
    "year": 2024,
    "title": "E-Summit 2024",
    "position": "Winner",
    "awardTier": "winner",
    "category": "Entrepreneurship & Pitching",
    "organization": "Entrepreneurship Cell",
    "description": "Awarded 1st prize for exemplary business viability, product scalability, and technological innovation.",
    "badge": "🏆 Winner",
    "featured": true,
    "tags": ["E-Summit", "Pitching", "Startup"]
  },
  {
    "id": "ach-2024-techexpo",
    "year": 2024,
    "title": "Tech Expo 2024",
    "position": "2nd Place",
    "awardTier": "runner-up",
    "category": "Technology Exhibition",
    "organization": "Annual Technology Expo",
    "description": "Awarded 2nd position among innovative hardware & software prototypes presented to industry jury.",
    "badge": "🥈 2nd Place",
    "featured": false,
    "tags": ["Expo", "Prototype", "Runner-Up"]
  },
  {
    "id": "ach-2024-iic",
    "year": 2024,
    "title": "IIC Regional Meet",
    "position": "Winner / Best Innovation",
    "awardTier": "winner",
    "category": "Innovation Council Meet",
    "organization": "MoE's Innovation Cell (IIC)",
    "description": "Recognized for breakthrough regional innovation project under Institution's Innovation Council initiative.",
    "badge": "🏆 Top Innovation",
    "featured": true,
    "tags": ["IIC", "Regional", "MoE"]
  },
  {
    "id": "ach-2024-innofusion1",
    "year": 2024,
    "title": "Innofusion 1.0",
    "position": "Winner",
    "awardTier": "winner",
    "category": "Innovation Hackathon",
    "organization": "Innofusion Tech Series",
    "description": "Secured the championship title with an end-to-end working solution built in a grueling timed sprint.",
    "badge": "🏆 Winner",
    "featured": false,
    "tags": ["Hackathon", "Innofusion", "Champion"]
  },
  {
    "id": "ach-2024-sih-finalist",
    "year": 2024,
    "title": "Smart India Hackathon (SIH) 2024",
    "position": "Finalist",
    "awardTier": "finalist",
    "category": "National Flagship Hackathon",
    "organization": "MoE & AICTE, Govt. of India",
    "description": "Consecutive national finalist selection at SIH 2024, representing institutional excellence in nationwide finals.",
    "badge": "🎖️ National Finalist",
    "featured": false,
    "tags": ["SIH", "National", "Finalist"]
  },
  {
    "id": "ach-2024-isro",
    "year": 2024,
    "title": "ISRO Space Hackathon",
    "position": "Winner",
    "awardTier": "winner",
    "category": "Space & Satellite Tech",
    "organization": "Indian Space Research Organisation (ISRO)",
    "description": "Clinched 1st place in the prestigious ISRO Space Hackathon solving advanced space and geospatial challenges.",
    "badge": "🏆 1st Prize Winner",
    "featured": true,
    "tags": ["ISRO", "Space Tech", "Govt", "Winner"]
  },
  {
    "id": "ach-2025-diversion",
    "year": 2025,
    "title": "Diversion Hackathon 2025",
    "position": "Best AI Hack Winner",
    "awardTier": "winner",
    "category": "Artificial Intelligence / ML",
    "organization": "Diversion International Hackathon",
    "description": "Won the prestigious 'Best AI Hack' title for building state-of-the-art machine learning & generative AI solutions.",
    "badge": "🏆 Best AI Hack Winner",
    "featured": true,
    "tags": ["AI", "Machine Learning", "Diversion"]
  },
  {
    "id": "ach-2025-sih-finalist",
    "year": 2025,
    "title": "Smart India Hackathon (SIH) 2025",
    "position": "Finalist",
    "awardTier": "finalist",
    "category": "National Flagship Hackathon",
    "organization": "MoE & AICTE, Govt. of India",
    "description": "Achieved consecutive third-year national finalist honor at Smart India Hackathon.",
    "badge": "🎖️ National Finalist",
    "featured": false,
    "tags": ["SIH", "Finalist", "Govt of India"]
  },
  {
    "id": "ach-2025-hack4bengal",
    "year": 2025,
    "title": "Hack4Bengal",
    "position": "Finalist & Virtual Hackathon Winner",
    "awardTier": "winner",
    "category": "Major Community Hackathon",
    "organization": "Hack4Bengal & Community",
    "description": "Grand finalist and crowned Winner of the Hack4Bengal Virtual Hackathon round among top developer teams.",
    "badge": "🏆 Winner & Finalist",
    "featured": true,
    "tags": ["Hack4Bengal", "Virtual Winner", "Community"]
  },
  {
    "id": "ach-2025-iitkgp-bplan",
    "year": 2025,
    "title": "IIT Kharagpur B-Plan Competition",
    "position": "2nd Runner-Up",
    "awardTier": "third-place",
    "category": "Business Plan & Innovation",
    "organization": "IIT Kharagpur",
    "description": "Secured 2nd Runner-Up position in IIT Kharagpur's highly competitive national business pitch competition.",
    "badge": "🥉 2nd Runner-Up",
    "featured": true,
    "tags": ["IIT Kharagpur", "B-Plan", "Venture"]
  },
  {
    "id": "ach-2025-metamorph",
    "year": 2025,
    "title": "Metamorph Hackathon",
    "position": "3rd Place",
    "awardTier": "third-place",
    "category": "Product Development Hackathon",
    "organization": "Metamorph",
    "description": "Awarded 3rd place for rapid prototyping and deployment of a resilient full-stack application.",
    "badge": "🥉 3rd Place",
    "featured": false,
    "tags": ["Hackathon", "Podium", "Product"]
  },
  {
    "id": "ach-2025-hackspire",
    "year": 2025,
    "title": "Hackspire Hackathon",
    "position": "2nd Place & Innovative Track Winner",
    "awardTier": "runner-up",
    "category": "Open Innovation & Technology",
    "organization": "Hackspire",
    "description": "Double recognition: 2nd Place overall and champion of the special Innovative Track.",
    "badge": "🥈 2nd Place + Track Win",
    "featured": true,
    "tags": ["Hackspire", "Track Winner", "Innovation"]
  },
  {
    "id": "ach-2025-innofusion2",
    "year": 2025,
    "title": "Innofusion 2.0",
    "position": "2nd Place",
    "awardTier": "runner-up",
    "category": "Innovation Hackathon",
    "organization": "Innofusion Tech Series",
    "description": "Bagged 2nd Place in the sequel edition, validating consistency in high-intensity problem solving.",
    "badge": "🥈 2nd Place",
    "featured": false,
    "tags": ["Innofusion", "Podium", "Runner-Up"]
  },
  {
    "id": "ach-2025-calcuttahack",
    "year": 2025,
    "title": "Calcutta Hack",
    "position": "4th Place",
    "awardTier": "finalist",
    "category": "Regional Flagship Hackathon",
    "organization": "Calcutta Hack Community",
    "description": "Secured 4th place ranking among hundreds of participating regional developer teams.",
    "badge": "🎖️ 4th Place Finalist",
    "featured": false,
    "tags": ["Calcutta Hack", "Top 4", "Regional"]
  },
  {
    "id": "ach-2026-colloquium",
    "year": 2026,
    "title": "New Year Colloquium Project Competition",
    "position": "Winner",
    "awardTier": "winner",
    "category": "Research & Project Showcase",
    "organization": "Academic & Research Colloquium",
    "description": "Kicked off 2026 with a 1st place victory in the New Year Colloquium project presentation.",
    "badge": "🏆 1st Prize Winner",
    "featured": true,
    "tags": ["Colloquium", "Project Showcase", "Winner"]
  },
  {
    "id": "ach-2026-iitbhu",
    "year": 2026,
    "title": "IIT-BHU Innovation Expo",
    "position": "Winner",
    "awardTier": "winner",
    "category": "National Innovation Expo",
    "organization": "IIT (BHU) Varanasi",
    "description": "Declared overall Winners at IIT-BHU Innovation Expo for outstanding engineering innovation.",
    "badge": "🏆 Grand Winner",
    "featured": true,
    "tags": ["IIT BHU", "Innovation Expo", "Grand Winner"]
  },
  {
    "id": "ach-2026-binary-algorand",
    "year": 2026,
    "title": "Binary V2 - Algorand Bounty Track",
    "position": "Bounty Track Winner",
    "awardTier": "special",
    "category": "Web3 & Blockchain",
    "organization": "Binary V2 & Algorand",
    "description": "Won the official Algorand ecosystem bounty track for decentralized application innovation.",
    "badge": "🌟 Algorand Bounty Winner",
    "featured": true,
    "tags": ["Web3", "Algorand", "Blockchain", "Bounty"]
  },
  {
    "id": "ach-2026-heliotropica",
    "year": 2026,
    "title": "Heliotropica 2K26",
    "position": "1st Winner",
    "awardTier": "winner",
    "category": "Annual Tech Symposium & Hackathon",
    "organization": "Heliotropica Fest",
    "description": "Clinched the 1st prize champion trophy at the annual Heliotropica 2K26 competition.",
    "badge": "🏆 1st Winner",
    "featured": true,
    "tags": ["Heliotropica", "1st Place", "Champion"]
  },
  {
    "id": "ach-2026-binary-overall",
    "year": 2026,
    "title": "Binary V2 Overall Championship",
    "position": "2nd Runner-Up",
    "awardTier": "third-place",
    "category": "Major Hackathon Championship",
    "organization": "Binary V2 Organizing Committee",
    "description": "Finished on the grand podium as 2nd Runner-Up in the overall Binary V2 Hackathon.",
    "badge": "🥉 2nd Runner Up (3rd Place)",
    "featured": true,
    "tags": ["Binary V2", "Podium", "Hackathon"]
  },
  {
    "id": "ach-2026-binary-open",
    "year": 2026,
    "title": "Binary V2 - Open Innovation Track",
    "position": "Track Winner",
    "awardTier": "winner",
    "category": "Open Innovation",
    "organization": "Binary V2",
    "description": "Secured 1st place track victory in the highly contested Open Innovation category.",
    "badge": "🏆 Open Innovation Winner",
    "featured": false,
    "tags": ["Binary V2", "Track Winner", "Open Innovation"]
  }
];

if (typeof window !== 'undefined') {
  window.INITIAL_ACHIEVEMENTS = INITIAL_ACHIEVEMENTS;
}

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { INITIAL_ACHIEVEMENTS };
}
